name: Playwright Tests with Reports
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
 
      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
 
      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci
 
      # 4. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
 
      # 5. Run Playwright tests with HTML reporter
      - name: Run Playwright tests
        run: npx playwright test --reporter=html
 
      # 6. Upload Playwright HTML report as artifact
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14