name: Playwright Tests with Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Cache node_modules
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 5. Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # 6. Run Playwright tests with HTML reporter
      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      # 7. Upload Playwright HTML report as artifact
      - name: Upload Playwright HTML report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
